### ISSUE TITLE
ARP Request에서 eth.dmac에 "00:00:00:00:00:00" 값이 들어감.

### ISSUE THREAD

**Issue by snoopspy** [SHJ99/arp-spoof#1]
ARP Request에서 eth.dmac에 "00:00:00:00:00:00" 값이 들어감.

https://github.com/SHJ99/arp-spoof/assets/4080232/911358aa-cf9c-4dfa-93a9-a8655213f181

**Comment by SHJ99** [comment]
Thank you sir!
